CREATE STREAM average_price_stream_rekeyed
  WITH (PARTITIONS=1) AS 
  SELECT CRYPTOCURRENY_NAME, FIVE_MINUTE_AVERAGE_PRICE, START_PERIOD, END_PERIOD, CRYPTOCURRENY_NAME + START_PERIOD + END_PERIOD as composite_key
   FROM AVERAGE_PRICE_STREAM_FROM_TABLE
   PARTITION BY CRYPTOCURRENY_NAME + START_PERIOD + END_PERIOD;
   