CREATE STREAM average_price_stream_rekeyed
  WITH (PARTITIONS=1) AS 
  SELECT CRYPTOCURRENCY_NAME, FIVE_MINUTE_AVERAGE_PRICE, START_PERIOD, END_PERIOD, CRYPTOCURRENCY_NAME + START_PERIOD + END_PERIOD as composite_key,
  ROWTIME as event_timestamp, START_PERIOD_TS, END_PERIOD_TS
   FROM AVERAGE_PRICE_STREAM_FROM_TABLE
   PARTITION BY CRYPTOCURRENCY_NAME + START_PERIOD + END_PERIOD;
   